FROM golang:1.23-alpine3.20

RUN go install github.com/go-delve/delve/cmd/dlv@latest
RUN go install github.com/air-verse/air@latest

ENV CGO_ENABLED=0 GOOS=linux GO111MODULE=on

WORKDIR /service

ARG VERSION
ENV VERSION=${VERSION}

ARG REVISION
ENV REVISION=${REVISION}

COPY go.mod go.sum ./
RUN go mod download

COPY . .

ENV GOCACHE=/root/.cache/go-build
RUN --mount=type=cache,target="/root/.cache/go-build" \
    go build \
    --ldflags "-X github.com/daronenko/backend-template/internal/config.Version=${VERSION} -X github.com/daronenko/backend-template/internal/config.Revision=${REVISION}" \
    -v -o ./bin/main ./cmd/app/main.go

COPY .air.toml ./

CMD ["air", "-c", ".air.toml"]
