FROM golang:1.23-alpine3.20

WORKDIR /service

RUN go install github.com/air-verse/air@latest

COPY go.mod go.sum ./
RUN go mod download

COPY .air.toml ./
COPY deploy/dev/config/config.yaml /etc/service/config.yaml

CMD ["air", "-c", ".air.toml"]
