networks:
  service-network:

services:
  service:
    image: daronenko/${SERVICE_NAME}:latest
    container_name: ${SERVICE_NAME}
    platform: linux/amd64
    env_file: .env
    build:
      dockerfile: deploy/dev/Dockerfile
      context: ../..
    ports:
      - ${SERVICE_PORT}:${SERVICE_PORT}
    restart: on-failure
    volumes:
      - ./config/config.yaml:/etc/service/config.yaml
    depends_on:
      postgres:
        condition: service_healthy
    networks:
      - service-network

  postgres:
    container_name: ${SERVICE_NAME}-postgres
    image: daronenko/${SERVICE_NAME}-postgres:latest
    build:
      dockerfile: postgres/Dockerfile
      context: .
    platform: linux/amd64
    env_file: .env
    environment:
      - POSTGRES_DB=${POSTGRES_DATABASE}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - PGDATA=/var/lib/postgresql/data/pgdata
    ports:
      - ${POSTGRES_PORT}:5432
    restart: on-failure
    volumes:
      - ./postgres/.pgdata:/var/lib/postgresql/data
      - ./postgres/config/postgresql.conf:/etc/postgresql/postgresql.conf
      - ./postgres/init:/docker-entrypoint-initdb.d
    command: postgres -c config_file=/etc/postgresql/postgresql.conf
    healthcheck:
      test:
        [
          'CMD-SHELL',
          "sh -c 'pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DATABASE}'",
        ]
      interval: 2s
      timeout: 3s
      retries: 3
    networks:
      - service-network
