service:
  name: backend-template

  adminKey:

  logger:
    level: debug
    devMode: false
    logsPath: /var/log/dump.log
    maxSize: 10
    maxBackups: 5
    maxAge: 30
    compress: true
  
  auth:
    jwtSecret: secretkey

    cookie:
      name: jwt-token
      maxAge: 86400
      secure: false
      httpOnly: true
  
    session:
      name: session-id
      prefix: api-session
      expire: 3600

postgres:
  host:
  port:
  user:
  password:
  database:
  sslMode:
  driver: pgx

redis:
  host:
  port:
  password:
  database: 0
  minIdleConns: 200
  poolSize: 12000
  poolTimeout: 240
