global:
  scrape_interval:     20s
  evaluation_interval: 20s

  external_labels:
      monitor: 'Host Server'

rule_files:
  - 'alerts/*.yml'

scrape_configs:
  - job_name: 'service'
    scrape_interval: 5s
    static_configs:
      - targets: ['service:8080']

  - job_name: 'nodeexporter'
    scrape_interval: 5s
    static_configs:
      - targets: ['nodeexporter:9100']

  - job_name: 'cadvisor'
    scrape_interval: 15s
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: 'prometheus'
    scrape_interval: 1m
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: 'loki'
    scrape_interval: 1m
    static_configs:
      - targets: ['loki:3100']

alerting:
  alertmanagers:
  - scheme: http
    static_configs:
    - targets: 
      - 'alertmanager:9093'
